import { ContextProvider } from "@/Context/Context";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <ContextProvider>
        <body>
          <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div><Navbar /></div>
            <div className={inter.className}>{children}</div>
          </div>
          
        </body>
      </ContextProvider>
    </html>
  );
}
